version: '3.5'

services:
  postgres_scheduler:
    container_name: postgres_scheduler
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/scheduler
    volumes:
       - scheduler:/data/scheduler
    ports:
      - "5432:5432"
    restart: always

volumes:
    scheduler: